# Generated by Django 3.1.6 on 2021-02-07 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_employment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='username', max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
